### ISSUE TITLE
405 error with full-archive search endpoint

### ISSUE THREAD

**Issue by sjisrawi** [twitterdev/search-tweets-python#119]
I am starting out with the sample code in the README with the full-archive search endpoint, but I keep getting a 405 "Method not allowed" error. I get the same error when using the command line app. Not sure if it's an issue with my credentials file or my query.

My credentials file: 

```
search_tweets_api:
  account_type: premium
  endpoint: https://api.twitter.com/2/tweets/search/all
  consumer_key: X
  consumer_secret: X
  bearer_token: X

search_tweets_fullarchive_dev:
  account_type: premium
  endpoint: https://api.twitter.com/2/tweets/search/all
  bearer_token: X
```

My code: 

```
from searchtweets import ResultStream, gen_rule_payload, load_credentials
from searchtweets import collect_results

premium_search_args = load_credentials("~/.twitter_keys.yaml", yaml_key="search_tweets_fullarchive_dev", env_overwrite=False)

rule = gen_rule_payload("from:jack", from_date="2017-09-01", to_date="2017-10-30", results_per_call=500)
# print(rule)
tweets = collect_results(rule, max_results=500, result_stream_args=premium_search_args)
[print(tweet.all_text) for tweet in tweets[0:10]];]
```
