### ISSUE TITLE
Adding all premium operators in API

### ISSUE THREAD

**Issue by vestronv** [twitterdev/search-tweets-python#24]
Is there a way we can extend API params to support all operators provided by Twitter Premium API(fullarchive or 30days). I tried adding `from: somename` in config.yaml file but didn't worked as expected.

**Comment by binaryaaron** [comment]
@vestronv - do you happen to have the full rule or yaml to share? It will make debugging a bit easier. Thanks!

**Comment by vestronv** [comment]
@binaryaaron  I tried `username: vimal` and also `from: vimal` in `search_params` of `[api_yaml_example](https://github.com/twitterdev/search-tweets-python/blob/master/tools/api_yaml_example.yaml)` file.

**Comment by binaryaaron** [comment]
@vestronv -

Do you mean your yaml file is like:

```
search_rules:
    from-date: 2017-06-01
    to-date: 2017-09-01 01:01
    pt-rule: kanye


search_params:
    results-per-call: 500
    max-results: 500
    from: vimal
```
If that is the case, note that the query operators are a part of a powertrack rule, in a string, rather than the parameters for the search function itself. `search_params` define information about how many results and results-per-api-call are defined. The premium search operators can only be used inside of the `pt-rule` field, as such:

```
search_rules:
    from-date: 2017-06-01
    to-date: 2017-09-01 01:01
    pt-rule: from:vimal
```

**Comment by vestronv** [comment]
But in case someone wants multiple rules like `query=some_keyword, from=somename, hashtag=some_hashtag, etc`. how can this be achieved ? I just tried adding another `pt-rule` and seems to overwriting previous one's.

**Comment by binaryaaron** [comment]
Ah, I think I understand what you're trying to achieve. 

a power track rule will look like this:

```
'(oscars OR "academy awards" OR #oscars) from:screename'
```
or 
```
(snow OR sleet OR hail OR (freezing rain)) has:images
```

The rule is a string that is passed to our API. So in the YAML file, you'd want to specify:

```
search_rules:
    from-date: 2017-06-01
    to-date: 2017-09-01 01:01
    pt-rule: "(snow OR sleet OR hail OR (freezing rain)) has:images"

```
