### ISSUE TITLE
ResultStream stream() function does not paginate

### ISSUE THREAD

**Issue by ophilbinbriscoe** [twitterdev/search-tweets-python#47]
I'm using a `ResultStream` object with search args from a `./.twitter_keys.yaml` config file that point at a premium FAS endpoint. Our subscription is for the maximum premium monthly rate limit of 2,500 requests.

My YAML file:
```
search_tweets_premium:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/:my_dev_env.json
  consumer_key: <my_key>
  consumer_secret: <my_secret>
```

My code (which I'm running from a Jupyter notebook):
```
from searchtweets import ResultStream, gen_rule_payload, load_credentials, collect_results

premium_search_args = load_credentials(filename="./.twitter_keys.yaml",
                 yaml_key="search_tweets_premium",
                 env_overwrite=False)

rule = gen_rule_payload("from:karenm_2000", results_per_call=500)
print(rule)

rs = ResultStream(rule_payload=rule,
                  max_results=500,
                  max_pages=100,
                  **premium_search_args)

tweets = list(rs.stream())
```
outputs...
```
{"query": "from:karenm_2000", "maxResults": 500}
searchtweets.result_stream - INFO - using bearer token for authentication
searchtweets.result_stream - INFO - ending stream at 38 tweets
```

After carefully doing a manual review of `@karenm_2000`'s timeline, we see that 38 is the number of tweets this user has published in the past 30 days (at the time of this writing). For whatever reason, `ResultStream` is stopping after 30 days instead of paginating through until it runs into one of the limiting args.
