### ISSUE TITLE
Error with load_credentials

### ISSUE THREAD

**Issue by fatimamb** [twitterdev/search-tweets-python#64]
hello 
after installing the packages I created a YAML file as shown here
```
search_tweets_premium:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json
  # if you have a bearer token, you can use it below. otherwise, swap the comment marks and use 
  # your app's consumer key/secret - the library will generate and use a bearer token for you. 
#bearer_token: <A_VERY_LONG_MAGIC_STRING> 
  consumer_key: <Sznpkb******************************>
  consumer_secret: <lP8Xr*****************************************************>
```
but when I run the code as shown here 
```
premium_search_args = load_credentials("C:/Users/DRC/Desktop/.twitter_keys.yaml",
                                       yaml_key="search_tweets_premium",
                                       env_overwrite=False)
```
I got this error 

```
cannot read file C:/Users/DRC/Desktop/.twitter_keys.yaml
Error parsing YAML file; searching for valid environment variables
Account type is not specified and cannot be inferred.
        Please check your credential file, arguments, or environment variables
        for issues. The account type must be 'premium' or 'enterprise'.
        

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-55-953b455c2646> in <module>
      1 premium_search_args = load_credentials("C:/Users/DRC/Desktop/.twitter_keys.yaml",
      2                                        yaml_key="search_tweets_premium",
----> 3                                        env_overwrite=False)

~\Anaconda3\lib\site-packages\searchtweets\credentials.py in load_credentials(filename, account_type, yaml_key, env_overwrite)
    187                    if env_overwrite
    188                    else merge_dicts(env_vars, yaml_vars))
--> 189     parsed_vars = _parse_credentials(merged_vars, account_type=account_type)
    190     return parsed_vars
    191 

~\Anaconda3\lib\site-packages\searchtweets\credentials.py in _parse_credentials(search_creds, account_type)
     80         """
     81         logger.error(msg)
---> 82         raise KeyError
     83 
     84     try:

KeyError:
```
if I modified the path in load_credentials and remove the dot before twitter_keys the error message change to be as shown here  
```
premium_search_args = load_credentials("C:/Users/DRC/Desktop/twitter_keys.yaml",
                                       yaml_key="search_tweets_premium",
                                       env_overwrite=False)
```
```
---------------------------------------------------------------------------
ScannerError                              Traceback (most recent call last)
<ipython-input-3-e34d8bf3703d> in <module>
      1 premium_search_args = load_credentials("C:/Users/DRC/Desktop/twitter_keys.yaml",
      2                                        yaml_key="search_tweets_premium",
----> 3                                        env_overwrite=False)

~\Anaconda3\lib\site-packages\searchtweets\credentials.py in load_credentials(filename, account_type, yaml_key, env_overwrite)
    179     filename = "~/.twitter_keys.yaml" if filename is None else filename
    180 
--> 181     yaml_vars = _load_yaml_credentials(filename=filename, yaml_key=yaml_key)
    182     if not yaml_vars:
    183         logger.warning("Error parsing YAML file; searching for "

~\Anaconda3\lib\site-packages\searchtweets\credentials.py in _load_yaml_credentials(filename, yaml_key)
     32     try:
     33         with open(os.path.expanduser(filename)) as f:
---> 34             search_creds = yaml.load(f)[yaml_key]
     35     except FileNotFoundError:
     36         logger.error("cannot read file {}".format(filename))

~\Anaconda3\lib\site-packages\yaml\__init__.py in load(stream, Loader)
     70     loader = Loader(stream)
     71     try:
---> 72         return loader.get_single_data()
     73     finally:
     74         loader.dispose()

~\Anaconda3\lib\site-packages\yaml\constructor.py in get_single_data(self)
     33     def get_single_data(self):
     34         # Ensure that the stream contains a single document and construct it.
---> 35         node = self.get_single_node()
     36         if node is not None:
     37             return self.construct_document(node)

~\Anaconda3\lib\site-packages\yaml\composer.py in get_single_node(self)
     34         document = None
     35         if not self.check_event(StreamEndEvent):
---> 36             document = self.compose_document()
     37 
     38         # Ensure that the stream contains no more documents.

~\Anaconda3\lib\site-packages\yaml\composer.py in compose_document(self)
     53 
     54         # Compose the root node.
---> 55         node = self.compose_node(None, None)
     56 
     57         # Drop the DOCUMENT-END event.

~\Anaconda3\lib\site-packages\yaml\composer.py in compose_node(self, parent, index)
     82             node = self.compose_sequence_node(anchor)
     83         elif self.check_event(MappingStartEvent):
---> 84             node = self.compose_mapping_node(anchor)
     85         self.ascend_resolver()
     86         return node

~\Anaconda3\lib\site-packages\yaml\composer.py in compose_mapping_node(self, anchor)
    131             #    raise ComposerError("while composing a mapping", start_event.start_mark,
    132             #            "found duplicate key", key_event.start_mark)
--> 133             item_value = self.compose_node(node, item_key)
    134             #node.value[item_key] = item_value
    135             node.value.append((item_key, item_value))

~\Anaconda3\lib\site-packages\yaml\composer.py in compose_node(self, parent, index)
     82             node = self.compose_sequence_node(anchor)
     83         elif self.check_event(MappingStartEvent):
---> 84             node = self.compose_mapping_node(anchor)
     85         self.ascend_resolver()
     86         return node

~\Anaconda3\lib\site-packages\yaml\composer.py in compose_mapping_node(self, anchor)
    125         if anchor is not None:
    126             self.anchors[anchor] = node
--> 127         while not self.check_event(MappingEndEvent):
    128             #key_event = self.peek_event()
    129             item_key = self.compose_node(node, None)

~\Anaconda3\lib\site-packages\yaml\parser.py in check_event(self, *choices)
     96         if self.current_event is None:
     97             if self.state:
---> 98                 self.current_event = self.state()
     99         if self.current_event is not None:
    100             if not choices:

~\Anaconda3\lib\site-packages\yaml\parser.py in parse_block_mapping_key(self)
    426 
    427     def parse_block_mapping_key(self):
--> 428         if self.check_token(KeyToken):
    429             token = self.get_token()
    430             if not self.check_token(KeyToken, ValueToken, BlockEndToken):

~\Anaconda3\lib\site-packages\yaml\scanner.py in check_token(self, *choices)
    113     def check_token(self, *choices):
    114         # Check if the next token is one of the given types.
--> 115         while self.need_more_tokens():
    116             self.fetch_more_tokens()
    117         if self.tokens:

~\Anaconda3\lib\site-packages\yaml\scanner.py in need_more_tokens(self)
    147         # The current token may be a potential simple key, so we
    148         # need to look further.
--> 149         self.stale_possible_simple_keys()
    150         if self.next_possible_simple_key() == self.tokens_taken:
    151             return True

~\Anaconda3\lib\site-packages\yaml\scanner.py in stale_possible_simple_keys(self)
    287                 if key.required:
    288                     raise ScannerError("while scanning a simple key", key.mark,
--> 289                             "could not find expected ':'", self.get_mark())
    290                 del self.possible_simple_keys[level]
    291 

ScannerError: while scanning a simple key
  in "C:/Users/DRC/Desktop/twitter_keys.yaml", line 5, column 3
could not find expected ':'
  in "C:/Users/DRC/Desktop/twitter_keys.yaml", line 7, column 3
```

is that because of bearer token?
or there is any mistake in my YAML file?

**Comment by jrmontag** [comment]
Hi @fatimamb, it looks like your error message is truncated in the snippet you posted. Can you update it to show the entire thing?

**Comment by fatimamb** [comment]
@jrmontag thank you for replying, but there is not truncated that is all the error message

**Comment by fionapigott** [comment]
Hi--in the YAML you pasted, the commented-out bearer token line isn't indented. I think that indentation matters in YAML files, if you delete that line and make sure that all of the keys underneath the main key are indented the same amount does it work?
Also yeah, seems like in the first example your code couldn't find the file at all, but it looks like it found it when you removed the "."

**Comment by jrmontag** [comment]
Hi @fatimamb, thanks for adding more context. The first argument to `load_credentials()` should be the path to the yaml file and have the appropriate name - if your yaml starts with a `.` character, then make sure that is reflected in the `load_credentials()` argument.

The exception is suggesting that the `account_type` isn't being read correctly, but in the snippet that you posted, I see you have set `account_type: premium` so that looks correct. Your snippet does include the `<` and `>` characters around your masked credentials. Those are intended to denote the example `<VERY_LONG_STRING>` but should not be included around your consumer key and secret. Once you verify that those characters are not present in the yaml, report back with the current exception you're seeing.

**Comment by fatimamb** [comment]
thank you @fionapigott and @jrmontag, 
I did what you wrote and I think it worked as shown here 
```
  search_tweets_fullarchive_dev:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json
  consumer_key: Szn************************************
  consumer_secret: lP8X************************************************
```
but I got another error
`Error parsing YAML file; searching for valid environment variables

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-33105a3d07eb> in <module>
      1 premium_search_args = load_credentials("C:/Users/DRC/Desktop/twitter_keys.yaml",
      2                                        yaml_key="search_tweets_fullarchive_dev",
----> 3                                        env_overwrite=False)

~\Anaconda3\lib\site-packages\searchtweets\credentials.py in load_credentials(filename, account_type, yaml_key, env_overwrite)
    186     merged_vars = (merge_dicts(yaml_vars, env_vars)
    187                    if env_overwrite
--> 188                    else merge_dicts(env_vars, yaml_vars))
    189     parsed_vars = _parse_credentials(merged_vars, account_type=account_type)
    190     return parsed_vars

~\Anaconda3\lib\site-packages\searchtweets\utils.py in merge_dicts(*dicts)
     82         return merged
     83 
---> 84     return reduce(_merge_dicts, dicts)
     85 
     86 

~\Anaconda3\lib\site-packages\searchtweets\utils.py in _merge_dicts(dict1, dict2)
     79     def _merge_dicts(dict1, dict2):
     80         merged = dict1.copy()
---> 81         merged.update(dict2)
     82         return merged
     83 

TypeError: 'NoneType' object is not iterable`

are this is environment variables?
```
export SEARCHTWEETS_ENDPOINT=
export SEARCHTWEETS_USERNAME=
export SEARCHTWEETS_PASSWORD=
export SEARCHTWEETS_BEARER_TOKEN=
export SEARCHTWEETS_ACCOUNT_TYPE=
export SEARCHTWEETS_CONSUMER_KEY=
export SEARCHTWEETS_CONSUMER_SECRET=
```

but where should I write them in YAML file or python file?
also, what are password and username? is it for my twitter account?

**Comment by igorbrigadir** [comment]
@fatimamb 

```yaml
  search_tweets_fullarchive_dev:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json
  consumer_key: Szn************************************
  consumer_secret: lP8X************************************************
```

It looks like there's 2 spaces before the YAML key `search_tweets_fullarchive_dev:` - it's still valid YAML format, but it's not what the code expects.

it should be: 

```yaml
search_tweets_fullarchive_dev:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json
  consumer_key: Szn************************************
  consumer_secret: lP8X************************************************
```

so that the key `search_tweets_fullarchive_dev` matches what the code is looking for `yaml_key="search_tweets_fullarchive_dev"`
